/** Auto-generated from affidavit-of-indigency.pdf — do not edit */
export const pdfFieldNames = [
  "Court",
  "Case Name and Number if known",
  "A I receive public assistance under check form of public assistance received",
  "Transitional Aid to Families with Dependent Children TAFDC",
  "Emergency Aid to Elderly Disabled or Children EAEDC",
  "Massachusetts Veterans Benefits Programs or",
  "Medicaid MassHealth",
  "Supplemental Security Income SSI",
  "persons consisting of myself and",
  "week",
  "biweekly",
  "month",
  "year",
  "check the period that applies for a household of",
  "which income is at or below the court systems poverty level Note The court systems poverty levels for households",
  "List any other available household income for the checked period on this line",
  "lower cost paid for by the state Check all that apply and in any",
  "guess as to the cost if known",
  "Filing fee and any surcharge",
  "Filing fee and any surcharge for appeal",
  "Fees or costs for serving court summons witness subpoenas or other court papers",
  "Other fees or costs of",
  "Substitution specify",
  "undefined",
  "undefined_2",
  "undefined_3",
  "for  specify",
  "undefined_4",
  "Cost",
  "of expert services for testing examination testimony or other assistance specify",
  "Cost_2",
  "of taking andor transcribing a deposition of specify name of person",
  "undefined_5",
  "Cassette copies of tape recording of trial or other proceeding needed to prepare appeal for applicant not",
  "Appeal bond",
  "Cost_3",
  "of preparing written transcript of trial or other proceeding",
  "undefined_6",
  "for  specify_2",
  "Other fees and costs",
  "Substitution specify_2",
  "undefined_7",
  "Date signed",
  "x",
  "B",
  "C",
  "applicantName",
  "residenceStreetAddress",
  "residenceCity",
  "residenceStateAndZip",
] as const;
export type PdfFieldName = (typeof pdfFieldNames)[number];
