/** Auto-generated from cjd400-motion-to-waive-publication.pdf — do not edit */
export const pdfFieldNames = [
  "Docket No",
  "DefendantRespondent",
  "Signature of attorney or plaintiff if pro se",
  "BBO",
  "Docket No_2",
  "name of party or attorney of record",
  "Address",
  "CityTown_2",
  "State_2",
  "Zip_2",
  "date of delivery",
  "By",
  "time",
  "mailing postage paid on",
  "date of mailing",
  "signature",
  "petitionerName",
  "date",
  "residenceStreetAddress",
  "residenceCity",
  "residenceState",
  "residenceZip",
  "phoneNumber",
  "printName",
  "division",
  "motionFor",
  "petitioner",
  "division2",
  "request",
  "currentLegalName",
  "motionFor2",
  "motionForPageTwo",
  "dated",
] as const;
export type PdfFieldName = (typeof pdfFieldNames)[number];
