/** Auto-generated from cjp27-petition-to-change-name-of-adult.pdf — do not edit */
export const pdfFieldNames = [
  "oldFirstName",
  "oldMiddleName",
  "oldLastName",
  "birthplaceCity",
  "birthplaceState",
  "dateOfBirth",
  "residenceStreetAddress",
  "residenceCity",
  "residenceState",
  "residenceZipCode",
  "mailingStreetAddress",
  "mailingCity",
  "mailingState",
  "mailingZipCode",
  "email",
  "previousNameFrom",
  "previousNameTo",
  "previousNameReason",
  "otherNamesOrAliases",
  "newFirstName",
  "newMiddleName",
  "newLastName",
  "hasUsedOtherNameOrAliasFalse",
  "hasUsedOtherNameOrAliasTrue",
  "shouldReturnOriginalDocuments",
  "hasPreviousNameChangeFalse",
  "hasPreviousNameChangeTrue",
  "phoneNumber",
  "petitionerFirstName",
  "petitionerMiddleName",
  "petitionerLastName",
  "county",
  "isInterpreterNeeded",
  "isOkayToSharePronouns",
  "pronouns",
  "language",
  "reasonForChangingName",
] as const;
export type PdfFieldName = (typeof pdfFieldNames)[number];
