/** Auto-generated from lic100-drivers-license-learners-permit-or-id-card.pdf — do not edit */
export const pdfFieldNames = [
  "Address",
  "DOB",
  "Gender change",
  "Height",
  "Eye color",
  "Type",
  "Document to Issue",
  "Class of Learner's Permit/License",
  "Service Type",
  "Last Name",
  "First Name",
  "Middle Name",
  "Suffix",
  "Current Massachusetts Learners Permit or Drivers License #",
  "Date of Birth",
  "Social Security Number",
  "Residential Address - Street",
  "Residential Address - Apt #",
  "Residential Address - City",
  "Residential Address - State",
  "Residential Address - Zip Code",
  "same as above",
  "Mailing Address - Street",
  "Mailing Address - Apt #",
  "Mailing Address - City",
  "Mailing Address - State",
  "Mailing Address - Zip Code",
  "Email",
  "Phone",
  "Emergency Contact Email",
  "Emergency Contact Name",
  "Emergency Contact Phone #",
  "Phone Type 1",
  "Phone Type 2",
  "Drivers License Learners Permit or ID Card",
  "Restrictions if applicable",
  "Country",
  "State",
  "Issue Date",
  "Expiration Date",
  "Height (feet, inches)",
  "What military branch",
  "If you are a veteran of the US Armed Forces do you",
  "Document Type",
  "Gender",
  "Eye Color",
  "Organ and tissue donor",
  "Donate to organ and tissue donor fund",
  "Citizen of the Unites States of America",
  "If yes where",
  "What credential class",
  "What credential #",
  "List any current license/permit",
  "License in another state, country, or jurisdiction",
  "Any impairment",
  "Any medication",
  "License suspended",
  "Date",
  "Person giving consent",
  "Name",
  "Foreign Passport",
  "Number",
  "Consular ID",
  "Have you had a MA permit, license, ID, or registration?",
  "Country of Issuance",
  "Name and number",
  "Are you an active duty member",
  "Are you a veteran",
  "Parent/Guardian's Address",
  "Parent/Guardian's Printed Name",
] as const;
export type PdfFieldName = (typeof pdfFieldNames)[number];
