/** Auto-generated from ss5-application-for-social-security-card.pdf — do not edit */
import { PDFCheckBox, PDFTextField } from "@cantoo/pdf-lib";

export const pdfSchema = {
  newFirstName: PDFTextField,
  newMiddleName: PDFTextField,
  newLastName: PDFTextField,
  oldFirstName: PDFTextField,
  oldMiddleName: PDFTextField,
  oldLastName: PDFTextField,
  otherNames: PDFTextField,
  birthplaceCity: PDFTextField,
  birthplaceState: PDFTextField,
  dateOfBirth: PDFTextField,
  usCitizen: PDFCheckBox,
  legalAlienAllowedToWork: PDFCheckBox,
  legalAlienNotAllowedToWork: PDFCheckBox,
  citizenshipOther: PDFCheckBox,
  isHispanicOrLatino: PDFCheckBox,
  isNotHispanicOrLatino: PDFCheckBox,
  isNativeHawaiian: PDFCheckBox,
  isAlaskaNative: PDFCheckBox,
  isAsian: PDFCheckBox,
  isAmericanIndian: PDFCheckBox,
  isBlack: PDFCheckBox,
  isOtherPacificIslander: PDFCheckBox,
  isWhite: PDFCheckBox,
  isMale: PDFCheckBox,
  isFemale: PDFCheckBox,
  mothersFirstName: PDFTextField,
  mothersMiddleName: PDFTextField,
  mothersLastName: PDFTextField,
  fathersFirstName: PDFTextField,
  fathersMiddleName: PDFTextField,
  fathersLastName: PDFTextField,
  hasPreviousSocialSecurityCard: PDFCheckBox,
  hasNoPreviousSocialSecurityCard: PDFCheckBox,
  previousSocialSecurityCardFirstName: PDFTextField,
  previousSocialSecurityCardMiddleName: PDFTextField,
  previousSocialSecurityCardLastName: PDFTextField,
  todaysDate: PDFTextField,
  phoneNumber: PDFTextField,
  mailingStreetAddress: PDFTextField,
  mailingCity: PDFTextField,
  mailingState: PDFTextField,
  mailingZipCode: PDFTextField,
  isSelf: PDFCheckBox,
  isParent: PDFCheckBox,
  isGuardian: PDFCheckBox,
  isFilingOther: PDFCheckBox,
  otherSpecify: PDFTextField,
  motherSSN1: PDFTextField,
  motherSSN2: PDFTextField,
  motherSSN3: PDFTextField,
  isMotherSSNUnknown: PDFCheckBox,
  fatherSSN1: PDFTextField,
  fatherSSN2: PDFTextField,
  fatherSSN3: PDFTextField,
  isFatherSSNUnknown: PDFCheckBox,
  differentDateOfBirthOnPreviousApplication: PDFTextField,
  previousSSN1: PDFTextField,
  previousSSN3: PDFTextField,
  previousSSN2: PDFTextField,
} as const;

export type PdfFieldName = keyof typeof pdfSchema;
